---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployments
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: deployments
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy deployments from Argo CD
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: ""
      kind: Deployment
  sourceRepos:
    - http://my-gitea-instance-gitea-http.gitea-dev.svc.cluster.local:3000/dev-admin/kubernetes-lab-argocd-configs.git