---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: namespaces
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: namespaces
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy Namespces from Argo CD
  destinations:
    - namespace: infra-argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  sourceRepos:
    - http://my-gitea-instance-gitea-http.gitea-dev.svc.cluster.local:3000/dev-admin/kubernetes-lab-argocd-configs.git