---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: services
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy services from Argo CD
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: ""
      kind: Service
  sourceRepos:
    - http://my-git-instance-pygitserver.git-server-dev.svc.cluster.local:8000/argocd-configs