---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc-apps
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: misc-apps
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: infra-argocd
    server: https://kubernetes.default.svc
  project: infra-argocd
  syncPolicy:
    automated: {}
  source:
    repoURL: https://charts.adfinis.com
    chart: misc-apps
    targetRevision: "*"
    helm:
      valuesObject:
        fullnameOverride: app
        argocdApps:
          enabled: true
          project: infra-argocd
          destination:
            server: https://kubernetes.default.svc
            namespace: infra-argocd
          syncPolicy:
            automated: {}
          values:
            applications:
              argocd-configs:
                namespace: infra-argocd
                project: infra-argocd
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/
                  repoURL: http://my-git-instance-pygitserver.git-server-dev.svc.cluster.local:8000/argocd-configs
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}
              appprojects:
                namespace: infra-argocd
                project: appprojects
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/appprojects
                  repoURL: http://my-git-instance-pygitserver.git-server-dev.svc.cluster.local:8000/argocd-configs
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}