---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc-apps
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: misc-apps
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  destination:
    namespace: infra-argocd
    server: https://kubernetes.default.svc
  project: argocd-apps
  syncPolicy:
    automated: {}
  source:
    repoURL: https://charts.adfinis.com
    chart: misc-apps
    targetRevision: "*"
    helm:
      valuesObject:
        fullnameOverride: app
        argocdApps:
          enabled: true
          project: infra-argocd
          destination:
            server: https://kubernetes.default.svc
            namespace: infra-argocd
          syncPolicy:
            automated: {}
          values:
            projects:
              infra-argocd:
                description: Deploy and manage the hosted Argo CD instance.
                sourceRepos:
                - https://argoproj.github.io/argo-helm
                - https://charts.adfinis.com
                - https://github.com/adfinis/argocd-configs.git'
                - http://my-gitea-instance-http.gitea-dev.svc.cluster.local:3000/dev-admin/kubernetes-lab-argocd-configs.git
                destinations:
                - namespace: infra-argocd
                  server: https://kubernetes.default.svc
                clusterResourceWhitelist:
                - group: ""
                  kind: Namespace
                - group: apiextensions.k8s.io
                  kind: CustomResourceDefinition
                - group: rbac.authorization.k8s.io
                  kind: ClusterRoleBinding
                - group: rbac.authorization.k8s.io
                  kind: ClusterRole
            applications:
              argocd-configs:
                namespace: infra-argocd
                project: argocd-apps
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/
                  repoURL: http://my-gitea-instance-http.gitea-dev.svc.cluster.local:3000/dev-admin/kubernetes-lab-argocd-configs.git
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}
              appprojects:
                namespace: infra-argocd
                project: appprojects
                destination:
                  namespace: infra-argocd
                  server: https://kubernetes.default.svc
                source:
                  path: manifests/dev/appprojects
                  repoURL: http://my-gitea-instance-http.gitea-dev.svc.cluster.local:3000/dev-admin/kubernetes-lab-argocd-configs.git
                  targetRevision: HEAD
                syncPolicy:
                  automated: {}